
name: Unit-tests on Linux GPU

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
        cuda_arch_version: ["12.4"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.g5.4xlarge.nvidia.gpu
      repository: pytorch/torchcodec
      gpu-arch-type: cuda
      gpu-arch-version: ${{ matrix.cuda_arch_version }}
      timeout: 120

      script: |
        nvidia-smi
        ls -l
        pwd
        conda create --yes --name test
        conda activate test
        conda install --yes pip cmake pkg-config nasm
        pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124
        conda install --yes nvidia::libnpp

        # Build and install FFMPEG from source with CUDA enabled.
        # The one on conda doesn't have CUDA enabled.
        # Sub-step: install nvidia headers. Reference this link for details:
        # https://docs.nvidia.com/video-technologies/video-codec-sdk/12.1/ffmpeg-with-nvidia-gpu/index.html
        git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
        pushd nv-codec-headers
        git checkout n11.0.10.1
        make PREFIX=$CONDA_PREFIX -j install
        popd

        # Now build FFMPEG from source with CUDA enabled.
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/
        pushd ffmpeg
        ./configure --prefix=$CONDA_PREFIX --enable-nonfree --enable-cuda-nvcc --enable-libnpp --disable-static --enable-shared --optflags=-fno-omit-frame-pointer --disable-stripping
        make -j install
        popd

        CMAKE_BUILD_PARALLEL_LEVEL=8 CXXFLAGS="" CMAKE_BUILD_TYPE=Release ENABLE_CUDA=1 ENABLE_NVTX=1 pip install -e . --no-build-isolation -vv --debug
        pip install pytest
        ffmpeg -version
        ffprobe -version
        pytest test
        conda deactivate
